name: Zhenglihui
title: Zhenglihui | A blog theme for Zhenglihui
description: Keep Learing.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email:lihui_zheng@qq.com
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
